version: '3.1'

services:
  springboot:
    image: devopsbynani/spring-boot-app:1.0.1
    restart: always
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=testdb
    - MONGO_DB_PASSWORD=testdb@123
    ports:
      - 8080:8086
    depends_on:
      - mongo
    networks:
    - springappnetwork  
    deploy: 
      replicas: 2
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5

  mongo:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=testdb
    - MONGO_INITDB_ROOT_PASSWORD=testdb@123
    volumes:
      - mongodb:/data/db
    restart: always
    networks:
    - springappnetwork
    
volumes:
  mongodb:
    driver: local
    
networks:
  springappnetwork: